TST: Adjust ExceptionInfo use for compatiblity with pytest v5.0.0
pytest v5.0.0 contains 65c2a8192 (Remove ExceptionInfo.__str__,
falling back to __repr__, 2019-06-06), which leads to calls like
`assert in str(exc)` failing with message like

    AssertionError: assert 'whatever' in '<ExceptionInfo ValueError tblen=2>'

We need to use the .value attribute, as some of our calls already
do.  (Other options would be to use the `match` keyword of
pytest.raises() or to call exc.match()).